spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jiakao?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888

mybatis-plus:
  type-aliases-package: com.mj.jk.pojo

logging:
  level:
    com.mj.jk.mapper: debug
